# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

# Use a package of configuration called an orb, see https://circleci.com/docs/2.0/orb-intro/
jobs:
  build:
    working_directory: ~/MDhandler
    docker:
      - image: circleci/python:3.6.4
  test:
    steps:
      - checkout
      - run:
          name: README.md compile test
          command: |
            . venv/bin/activate
            pytest -q readmewriter.py

workflows:
  build_test:
    jobs:
      - build
      - test